# Configuration for development and testing environment

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=task_management
    networks:
      - app-network

  # Backend with Serverless
  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGODB_DB_NAME=task_management
      - REGION=us-east-1
      - COGNITO_USER_POOL_ID=local_cognito_pool
      - COGNITO_CLIENT_ID=local_client_id
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network

  # Frontend with React
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3000/dev
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local