AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for deploying the Task Manager frontend to Amplify'

Parameters:
  GitHubOwner:
    Type: String
    Description: GitHub repository owner
  
  GitHubRepo:
    Type: String
    Description: GitHub repository name
  
  GitHubBranch:
    Type: String
    Default: main
    Description: GitHub repository branch
  
  GitHubOAuthToken:
    Type: String
    NoEcho: true
    Description: GitHub OAuth token

Resources:
  TaskManagerAmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: TaskManagerApp
      Repository: !Sub https://github.com/${GitHubOwner}/${GitHubRepo}
      AccessToken: !Ref GitHubOAuthToken
      BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - cd frontend
                - npm ci
            build:
              commands:
                - cd frontend
                - npm run build
          artifacts:
            baseDirectory: frontend/build
            files:
              - '**/*'
          cache:
            paths:
              - 'frontend/node_modules/**/*'
      EnvironmentVariables:
        - Name: REACT_APP_API_URL
          Value: https://hqiey3eg22.execute-api.us-east-1.amazonaws.com/dev
      IAMServiceRole: !GetAtt AmplifyServiceRole.Arn

  TaskManagerBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt TaskManagerAmplifyApp.AppId
      BranchName: !Ref GitHubBranch
      EnableAutoBuild: true

  AmplifyServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

Outputs:
  DefaultDomain:
    Description: 'Default domain for the Amplify app'
    Value: !GetAtt TaskManagerAmplifyApp.DefaultDomain
  
  AppURL:
    Description: 'URL to the app'
    Value: !Sub https://${GitHubBranch}.${TaskManagerAmplifyApp.DefaultDomain} 